# .streamlit/secrets.toml
FMP_API_KEY = "8SlrrwvD30SGOUTEO8JHKo9Hzw4npEhS"
ALPHA_VANTAGE_API_KEY='Y16JFTL2T7VKTAEA'
FRED_API_KEY='c7b309aa3f21af8684c45167a0d20dd6'
FINNHUB_API_KEY='d08esmpr01qh1ecbourgd08esmpr01qh1ecbous0'